# -*- mode: ruby -*-
# vi: set ft=ruby :
# Author: Alejandro Galue <agalue@opennms.org>

minion = {
  :name      => "Telemetry-Minion",
  :host      => "minion.local",
  :ip        => "192.168.205.142",
  :mem       => "1024",
  :cpu       => "2",
  :onms_repo => "opennms-22",
  :onms_ver  => "-latest-",
  :location  => "Vagrant"
}

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.define minion[:name] do |config|
    config.vm.hostname = minion[:host]
    config.vm.provider "virtualbox" do |v|
      v.name = minion[:name]
      v.customize [ "modifyvm", :id, "--cpus", minion[:cpu] ]
      v.customize [ "modifyvm", :id, "--memory", minion[:mem] ]
    end
    config.vm.network "private_network", ip: minion[:ip]
    config.vm.provision "shell" do |s|
      s.path = "bootstrap-minion.sh"
      s.args = [ minion[:onms_repo], minion[:onms_ver], minion[:location] ]
    end
  end

end
