# -*- mode: ruby -*-
# vi: set ft=ruby :
# Author: Alejandro Galue <agalue@opennms.org>

opts = {
  :mem       => "1024",
  :cpu       => "1",
  :onms_repo => "branches-cg-jira-NMS-10300",
  :onms_ver  => "-latest-",
  :location  => "Vagrant",
  :timezone  => "America/New_York"
}

boxes = [
  {
    :name => "Telemetry-Minion-01",
    :host => "minion01.local",
    :ip   => "192.168.205.141"
  }, {
    :name => "Telemetry-Minion-02",
    :host => "minion02.local",
    :ip   => "192.168.205.142"
  }
]

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  boxes.each do |box|
    config.vm.define box[:name] do |config|
      config.vm.hostname = box[:host]
      config.vm.provider "virtualbox" do |v|
        v.name = box[:name]
        v.customize [ "modifyvm", :id, "--cpus", opts[:cpu] ]
        v.customize [ "modifyvm", :id, "--memory", opts[:mem] ]
      end
      config.vm.network "private_network", ip: box[:ip]
      config.vm.provision "shell" do |s|
        s.path = "bootstrap-minion.sh"
        s.args = [ opts[:onms_repo], opts[:onms_ver], opts[:location], opts[:timezone] ]
      end
    end
  end
end
